apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bucketlist-stateless
  name: bucketlist-stateless
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bucketlist-stateless
  type: LoadBalancer
status:
  loadBalancer: {}
